objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountIntegrationId__c</fullName>
        <description>Account Integration Id (concatena 11 digitos del Customer Integration Id y 5 del Billing Integration Id)</description>
        <externalId>true</externalId>
        <inlineHelpText>Account Integration Id (concatena 11 digitos del Customer Integration Id y 5 del Billing Integration Id)</inlineHelpText>
        <label>Account Integration Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__OneTimeTotal__c</fullName>
        <label>One Time Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OrderProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Order Product from which this asset was created or most recently updated.</description>
        <label>Order Product</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>DeliveryDate__c</fullName>
        <description>Delivery Date - xOM</description>
        <inlineHelpText>Delivery Date - xOM</inlineHelpText>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gestion__c</fullName>
        <label>Gestion</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cambio de SIM</fullName>
                </value>
                <value>
                    <fullName>Cambio de SIM por siniestro</fullName>
                </value>
                <value>
                    <fullName>Cambio de número</fullName>
                </value>
                <value>
                    <fullName>Cambio de titularidad</fullName>
                </value>
                <value>
                    <fullName>Desconexión</fullName>
                </value>
                <value>
                    <fullName>Nominacion</fullName>
                </value>
                <value>
                    <fullName>Cambio de Plan</fullName>
                </value>
                <value>
                    <fullName>Alta Baja Servicios</fullName>
                </value>
                <value>
                    <fullName>Compra de Pack</fullName>
                </value>
                <value>
                    <fullName>Venta</fullName>
                </value>
                <value>
                    <fullName>Alta</fullName>
                </value>
                <value>
                    <fullName>Recarga</fullName>
                </value>
                <value>
                    <fullName>Preactivacion Repro</fullName>
                </value>
                <value>
                    <fullName>Alta o Baja SVA</fullName>
                </value>
                <value>
                    <fullName>Conciliador</fullName>
                </value>
                <value>
                    <fullName>Conciliate</fullName>
                </value>
                <value>
                    <fullName>Suspension</fullName>
                </value>
                <value>
                    <fullName>Resume</fullName>
                </value>
                <value>
                    <fullName>Numero Gratis</fullName>
                </value>
                <value>
                    <fullName>Alta producto genérico</fullName>
                </value>
                <value>
                    <fullName>Cambio de Terminal</fullName>
                </value>
                <value>
                    <fullName>Cambio en Garantia</fullName>
                </value>
                <value>
                    <fullName>Reseteo de Cuota</fullName>
                </value>
                <value>
                    <fullName>Cambio de tiularidad</fullName>
                    <isActive>false</isActive>
                    <label>Cambio de tiularidad</label>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                    <isActive>false</isActive>
                    <label>Dormant</label>
                </value>
                <value>
                    <fullName>SimcardChange</fullName>
                    <isActive>false</isActive>
                    <label>SimcardChange</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OriginStoreLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Origin Store Location</label>
        <referenceTo>vlocity_cmt__BusinessSite__c</referenceTo>
        <relationshipLabel>Orders (Origin Store Location)</relationshipLabel>
        <relationshipName>OriginOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PaymentMethodType__c</fullName>
        <label>Payment Method Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PaymentMethodType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubGestion__c</fullName>
        <description>Used to identify the subtype of Gestion performed. This field depends on Gestion__c value. Initially created to identify the subtypes of Cambio En Garantía (Replacement Warranty).</description>
        <label>SubGestion</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Gestion__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Orden de ST</fullName>
                </value>
                <value>
                    <fullName>Fallas reiteradas</fullName>
                </value>
                <value>
                    <fullName>Ley de defensa del consumidor</fullName>
                </value>
                <value>
                    <fullName>Terminal sin ST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OneTimeTotal__c</fullName>
        <label>Total: One Time Charges</label>
        <summarizedField>OrderItem.vlocity_cmt__OneTimeTotal__c</summarizedField>
        <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OriginatingChannel__c</fullName>
        <description>Channel can be used to drive Eligibility/Compatibility/Recommendations/Pricing/Other implementations, e.g. Certain Product Bundles are only available on the Web or Call Center channel but not via the Retail and Dealer channels OR A product may have a different price when sold via the Web than sold via the Retail channel, etc.</description>
        <label>Originating Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WEB</fullName>
                </value>
                <value>
                    <fullName>Call Center</fullName>
                </value>
                <value>
                    <fullName>Retails</fullName>
                </value>
                <value>
                    <fullName>Mayorista</fullName>
                </value>
                <value>
                    <fullName>Agentes</fullName>
                </value>
                <value>
                    <fullName>Oficinas Comerciales</fullName>
                </value>
                <value>
                    <fullName>E-Commerce</fullName>
                </value>
                <value>
                    <fullName>Administración de Ventas</fullName>
                </value>
                <value>
                    <fullName>APP</fullName>
                </value>
                <value>
                    <fullName>Cooperativas</fullName>
                </value>
                <value>
                    <fullName>Ejecutivos</fullName>
                </value>
                <value>
                    <fullName>Emprendimientos</fullName>
                </value>
                <value>
                    <fullName>IVR</fullName>
                </value>
                <value>
                    <fullName>SMS</fullName>
                </value>
                <value>
                    <fullName>Social Media</fullName>
                </value>
                <value>
                    <fullName>USSD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>LocationCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A Location is set here, when the orderItem belongs to a Simcard and has a LineNumber associated to identify the location where the line is assigned</description>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OneTimeTotal__c</fullName>
        <description>Final total after all pricing and * Quantity</description>
        <label>One Time Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__SerialNumber__c</fullName>
        <label>Serial Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Team_Member__c.object
<CustomObject>
    <description>Store the user assigned by work team in TA, this object is used to handle the security.</description>
    <label>Work Team Member</label>
    <nameField>
        <displayFormat>T-{00000000}</displayFormat>
        <label>Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__BusinessSite__c.object
<CustomObject>
    <description>Sites track the service and retail locations where customers may obtain products or services from your organization or your partner organizations. In the communications industry, these represent retail stores or customer service locations. In the public sector, these represent the locations where benefits service providers operate. A site is located by address as well as geo-location data. A site must be defined for an account which may be a partner account or an internal organization account used to describe your company.</description>
    <fields>
        <fullName>Channel_Type_2__c</fullName>
        <description>Stores the level 2 of the type of channels.</description>
        <label>Channel Type 2</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Channel_Type_3__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>ChannelType2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel_Type_3__c</fullName>
        <description>Stores the level 3 of the type of channels.</description>
        <label>Channel Type 3</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ChannelType3</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel_Type__c</fullName>
        <description>Stores the first level of the type of channels.</description>
        <label>Channel Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Channel_Type_2__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>ChannelType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <description>Used to indicate the top level of the channels in the solution based in the value selected in the Channel_Type__c field.</description>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Channel_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Channel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Store the region that the store location belongs to.</description>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Used to indicate the status of the point of sales or agency.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Dado de baja</fullName>
                </value>
                <value>
                    <fullName>Activo</fullName>
                </value>
                <value>
                    <fullName>Pendiente activación</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>POS</fullName>
                </value>
                <value>
                    <fullName>PostOffice</fullName>
                    <label>Post Office</label>
                </value>
                <value>
                    <fullName>Agente</fullName>
                </value>
                <value>
                    <fullName>Proveedor</fullName>
                </value>
                <value>
                    <fullName>Oficina Comercial</fullName>
                </value>
                <value>
                    <fullName>Deposito Central TP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OrganizationId__c</fullName>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>OrganizationSites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Site</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/WorkTeam__c.object
<CustomObject>
    <description>Custom Object used to store the work teams hierarchy used to handle the security at Business Process level.</description>
    <fields>
        <fullName>Team_Name__c</fullName>
        <description>Stores the name of the division (team).</description>
        <externalId>true</externalId>
        <label>Team Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Work Team</label>
    <nameField>
        <label>Work Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/taSalesChangeTerminalInWarrantyTest.cls
@isTest
public class taSalesChangeTerminalInWarrantyTest
{
  Public static testmethod void test1()
  {
    List<Account> lstAccount = TestDataFactory.createAccounts(1, 'Consumer');
    List<Product2> lstProduct2 = TestDataFactory.createProduct(1);
    Asset assetTest = new Asset();
    assetTest.Name = 'Test Asset';
    assetTest.AccountId = lstAccount[0].Id;
    assetTest.Product2Id =  lstProduct2[0].Id;
    lstProduct2[0].productCode = 'CHIPPRUEBA';
    update lstProduct2;
    insert assetTest;
    vlocity_cmt__BusinessSite__c storeLocation = new vlocity_cmt__BusinessSite__c(
      Name = 'Barrio Norte',
      vlocity_cmt__OrganizationId__c = lstAccount[0].Id,
      Status__c = 'Activo',
      Type__c = 'POS',
      Channel__c = 'Físico',
      Channel_Type__c = 'Agentes',
      Channel_Type_2__c = 'Agentes',
      Channel_Type_3__c = 'Agentes',
      Region__c='AMBA');
    insert storeLocation;

        WorkTeam__c workTeamParent = new WorkTeam__c(
      Team_Name__c = 'Test Parent',
      Name = 'Test Parent');
        insert workTeamParent;

    AnnulmentTimeLimit__c objTimeAnnul = new AnnulmentTimeLimit__c();
    objTimeAnnul.Channel__c = 'Físico';
    objTimeAnnul.LocationCode__c = 'C';
    objTimeAnnul.Name = 'CABA_Fisico';
    objTimeAnnul.TimeLimit__c = 30.0;
    insert objTimeAnnul;

    User usernew = new user(ID = UserInfo.getUserID());
        String strIdUser = UserInfo.getUserID();

        String manager = UserInfo.getUserId();
        String parent = workTeamParent.Id;
        WorkTeam__c workTeam = new WorkTeam__c(Team_Name__c = 'Test', Name = 'Test');
    Team_Member__c tm = TestDataFactory.setTeamMember('Call Center', UserInfo.getUserId(), null);
    List<Order>OrdList = TestDataFactory.createOrders(2,lstAccount[0]);
    OrdList[0].OriginStoreLocation__c = storeLocation.Id;
    OrdList[0].PaymentMethodType__c ='1001';
    OrdList[0].vlocity_cmt__OriginatingChannel__c ='Presencial Oficina Comercial';
    OrdList[0].Gestion__c = 'Venta';
    OrdList[1].SubGestion__c = '';
    OrdList[1].OriginStoreLocation__c = storeLocation.Id;
    OrdList[1].PaymentMethodType__c ='1001';
    OrdList[1].vlocity_cmt__OriginatingChannel__c ='Presencial Oficina Comercial';
    OrdList[1].Gestion__c = 'Venta';
    OrdList[1].SubGestion__c = '';
    update OrdList;
    Map<String, Object> inputMap = new Map<String, Object>();
    Map<String, Object> outputMap = new Map<String, Object>();
    Map<String, Object> options = new Map<String, Object>();
    options.put('assetId', assetTest.Id);
    Test.startTest();
      taSalesChangeTerminalInWarrantyHandler tsctiw = new taSalesChangeTerminalInWarrantyHandler();
      tsctiw.invokeMethod('ValidateCEGRazonSocial', inputMap, outputMap, options);
      tsctiw.invokeMethod('validationTimeDefenseConsumer', inputMap, outputMap, options);
    Test.stopTest();
  }

  public static testmethod void ChangeTerminalInWarrantyHandlerTest()
  {
    Account account = TestDataFactory.createAccounts(1, 'Consumer')[0];
    account.AccountIntegrationId__c = '10000000564';
    update account;

    vlocity_cmt__BusinessSite__c storeLocation = new vlocity_cmt__BusinessSite__c(
      Name = 'Barrio Norte',
      vlocity_cmt__OrganizationId__c = Account.Id,
      Status__c = 'Activo',
      Type__c = 'POS',
      Channel__c = 'Físico',
      Channel_Type__c = 'Agentes',
      Channel_Type_2__c = 'Agentes',
      Channel_Type_3__c = 'Agentes',
      Region__c='AMBA');
    insert storeLocation;

    WorkTeam__c workTeamParent = new WorkTeam__c(
      Team_Name__c = 'Test Parent',
      Name = 'Test Parent');
      insert workTeamParent;

    User usernew = new user(ID = UserInfo.getUserID());
        String strIdUser = UserInfo.getUserID();

        String manager = UserInfo.getUserId();
        String parent = workTeamParent.Id;
        WorkTeam__c workTeam = new WorkTeam__c(Team_Name__c = 'Test', Name = 'Test');
    Team_Member__c tm = TestDataFactory.setTeamMember('Call Center', UserInfo.getUserId(), null);

    List<Order> ordList = TestDataFactory.createOrders(1, account);
    Order ord1 = ordList[0];
    Order order1 = [SELECT Id FROM Order WHERE Id = :ord1.Id];
    order1.Name = 'OrderTestVPA1';
    order1.OriginStoreLocation__c = storeLocation.Id;
    order1.DeliveryDate__c = Date.parse('04/04/2018');
    update order1;

    List<OrderItem> itemsList = new List<OrderItem>();
    List<OrderItem> itemsList1 = TestDataFactory.createOrderItem(1, order1);
    itemsList1[0].vlocity_cmt__OneTimeTotal__c  = 0;
    itemsList1[0].vlocity_cmt__SerialNumber__c  = '89543410307680582547';
    itemsList.add(itemsList1[0]);
    update itemsList;

    // Se setea el id de orderItem en asset para relacionarlo como order creadora del asset
    OrderItem ordItem1 = itemsList1[0];
    Asset asset = TestDataFactory.CreateAssets(1, account)[0];
    asset.vlocity_cmt__OrderProductId__c = ordItem1.Id;
    update asset;


 /*   AnnulmentAvailableChannels__c annulmentAvailableChannels = new AnnulmentAvailableChannels__c(
      Name = 'Test',
      OriginChannel__c = 'Oficinas Comerciales',
      AnnulmentChannel__c = 'Oficinas Comerciales');
    insert annulmentAvailableChannels; */

  //  List<vlocity_cmt__PaymentAdjustment__c> paymentAdjustmentList = TestDataFactory.createPaymentAdjustments(1, account, order1, null, 1);

    Map<String, Object> inputMap = new Map<String, Object>();
    Map<String, Object> outputMap = new Map<String, Object>();
    Map<String, Object> options = new Map<String, Object>();
    //options.put('OrderID', order1.Id);
    //options.put('orderId', order1.Id);
    options.put('assetId', asset.Id);

    Test.startTest();
      taSalesChangeTerminalInWarrantyHandler tsctiw = new taSalesChangeTerminalInWarrantyHandler();
      tsctiw.invokeMethod('ValidateCEGRazonSocial', inputMap, outputMap, options);
    Test.stopTest();
  }
}