objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Asset_Brand__c</fullName>
        <label>Asset Brand</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Linked_Product_Family__c</fullName>
        <formula>TEXT(Product2.Family)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Linked Product Family</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MSISDN__c</fullName>
        <description>MSISDN Line number</description>
        <inlineHelpText>MSISDN Line number</inlineHelpText>
        <label>MSISDN</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <description>Field to descript the reason a status had been apply for an asset</description>
        <label>Sub Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Siniestro</fullName>
                </value>
                <value>
                    <fullName>Fraude</fullName>
                </value>
                <value>
                    <fullName>Port-out</fullName>
                </value>
                <value>
                    <fullName>Mora</fullName>
                </value>
                <value>
                    <fullName>Línea suspendida por mora</fullName>
                </value>
                <value>
                    <fullName>Línea suspendida por fraude</fullName>
                </value>
                <value>
                    <fullName>Línea suspendida voluntariamente</fullName>
                </value>
                <value>
                    <fullName>Línea suspendida por siniestro</fullName>
                </value>
                <value>
                    <fullName>Línea suspendida por Dorma</fullName>
                </value>
                <value>
                    <fullName>Suspend-Siniestro</fullName>
                </value>
                <value>
                    <fullName>Suspend-Fraude</fullName>
                </value>
                <value>
                    <fullName>Suspend-Voluntaria</fullName>
                </value>
                <value>
                    <fullName>Mora-Parcial</fullName>
                </value>
                <value>
                    <fullName>Mora-Total</fullName>
                </value>
                <value>
                    <fullName>Administrativo</fullName>
                </value>
                <value>
                    <fullName>PortOut</fullName>
                </value>
                <value>
                    <fullName>Resume-Cliente</fullName>
                </value>
                <value>
                    <fullName>Resume-Operador</fullName>
                </value>
                <value>
                    <fullName>Resume-Extravio</fullName>
                </value>
                <value>
                    <fullName>Siniestro/Extravio</fullName>
                </value>
                <value>
                    <fullName>Suspend-PortOut</fullName>
                </value>
                <value>
                    <fullName>Conciliate</fullName>
                </value>
                <value>
                    <fullName>Suspend-Robo</fullName>
                </value>
                <value>
                    <fullName>Suspend-Hurto</fullName>
                </value>
                <value>
                    <fullName>Suspend-Extravio</fullName>
                </value>
                <value>
                    <fullName>Robo</fullName>
                </value>
                <value>
                    <fullName>Hurto</fullName>
                </value>
                <value>
                    <fullName>Extravio</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>assetModel__c</fullName>
        <label>Asset Model</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>imei__c</fullName>
        <label>Imei</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__ActivationDate__c</fullName>
        <description>The date when this asset was activated.</description>
        <inlineHelpText>Activation Date for this Asset</inlineHelpText>
        <label>Activation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__ProvisioningStatus__c</fullName>
        <description>The current provisioning, or fulfillment, status of the asset with values such as New, Active, Changed or Deleted.</description>
        <label>Provisioning Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>Delivery_Method__c</fullName>
        <label>Delivery Method</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>vlocity_cmt__OriginatingChannel__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Delivery_Methods</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OriginatingChannel__c</fullName>
        <description>Channel can be used to drive Eligibility/Compatibility/Recommendations/Pricing/Other implementations, e.g. Certain Product Bundles are only available on the Web or Call Center channel but not via the Retail and Dealer channels OR A product may have a different price when sold via the Web than sold via the Retail channel, etc.</description>
        <label>Originating Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WEB</fullName>
                </value>
                <value>
                    <fullName>Call Center</fullName>
                </value>
                <value>
                    <fullName>Retails</fullName>
                </value>
                <value>
                    <fullName>Mayorista</fullName>
                </value>
                <value>
                    <fullName>Agentes</fullName>
                </value>
                <value>
                    <fullName>Oficinas Comerciales</fullName>
                </value>
                <value>
                    <fullName>E-Commerce</fullName>
                </value>
                <value>
                    <fullName>Administración de Ventas</fullName>
                </value>
                <value>
                    <fullName>APP</fullName>
                </value>
                <value>
                    <fullName>Cooperativas</fullName>
                </value>
                <value>
                    <fullName>Ejecutivos</fullName>
                </value>
                <value>
                    <fullName>Emprendimientos</fullName>
                </value>
                <value>
                    <fullName>IVR</fullName>
                </value>
                <value>
                    <fullName>SMS</fullName>
                </value>
                <value>
                    <fullName>Social Media</fullName>
                </value>
                <value>
                    <fullName>USSD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__ProvisioningStatus__c</fullName>
        <description>(NOTE: The functionality of this field is replaced by the Action, Sub-Action and Fulfilment Status fields.) The desired provisioning action for the asset identified on this line item. Values include New (add), Active (no change), Changed or Deleted.</description>
        <label>Provisioning Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__SubAction__c</fullName>
        <description>The sub-action requested for this line item typically used for moves of service from one location to another with values of Move-Add and Move-Delete. Move-Add means this item is being added as part of the move and usually should be added before the previous service is disconnected. Move-Delete means this item is the service to be disconnected after the service is activated at the new location.</description>
        <label>Sub Action</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Move</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Full suspend</fullName>
                </value>
                <value>
                    <fullName>Baja-Baja</fullName>
                </value>
                <value>
                    <fullName>Baja-PortOut</fullName>
                </value>
                <value>
                    <fullName>Conciliate</fullName>
                </value>
                <value>
                    <fullName>Suspend-Fraude</fullName>
                </value>
                <value>
                    <fullName>Suspend-Voluntaria</fullName>
                </value>
                <value>
                    <fullName>Suspend-Portabilidad</fullName>
                </value>
                <value>
                    <fullName>Suspend-Siniestro</fullName>
                </value>
                <value>
                    <fullName>Resume-Siniestro</fullName>
                </value>
                <value>
                    <fullName>Resume-Fraude</fullName>
                </value>
                <value>
                    <fullName>Resume-Voluntaria</fullName>
                </value>
                <value>
                    <fullName>Change</fullName>
                </value>
                <value>
                    <fullName>Suspend-Robo</fullName>
                </value>
                <value>
                    <fullName>Suspend-Hurto</fullName>
                </value>
                <value>
                    <fullName>Suspend-Extravio</fullName>
                </value>
                <value>
                    <fullName>Resume-Portabilidad</fullName>
                    <isActive>false</isActive>
                    <label>Resume-Portabilidad</label>
                </value>
                <value>
                    <fullName>Suspend-Operador</fullName>
                    <isActive>false</isActive>
                    <label>Suspend-Operador</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/taCareSuspensionsAndReconnections2.cls
global class taCareSuspensionsAndReconnections2 implements vlocity_cmt.VlocityOpenInterface
{

    global Boolean invokeMethod(String methodName, Map<String, Object> input, Map<String, Object> outMap, Map<String, Object> options) {

        try
        {
            if (methodName.equals('createOrder')) {
                createOrder(input, outMap, options);
            }
            if (methodName.equals('createOrderBackoffice')) {
                createOrderBackoffice(input, outMap, options);
            }
            if (methodName.equals('getActiveOrSuspendedAssets')) {
                getActiveOrSuspendedAssets(input, outMap, options);
            }
            if (methodName.equals('createListChildCasesUnfraudBA')) {
                createListChildCasesUnfraudBA(input, outMap, options);
            }
            if (methodName.equals('createListChildCasesFraudBA')) {
                createListChildCasesFraudBA(input, outMap, options);
            }
            if (methodName.equals('createListChildCasesAssets')) {
                createListChildCasesAssets(input, outMap, options);
            }
            return true;
        }
        catch(Exception e)
        {
            outMap.put('error', e.getMessage() + e.getStackTraceString());
            System.debug('taCareSuspensionsAndReconnections:invokeMethod -> exception: '+e);
            return false;
        }
    }




private void createOrderBackoffice(Map<String,Object> inputMap, Map<String,Object> outMap, Map<String,Object> options) {
        
         Map<String,Object> step3 = (Map<String,Object>)inputMap.get('Step3');
         List<Object> AssetsM = (List<Object>) step3.get('AssetsM');
         Map<String,Object> selectedAsset = (Map<String,Object>) AssetsM[0];
         
         AssetsM = new List<Object>(); 
         step3 = new Map<String,Object>();
         
         ///////////////Crear order a partir de un Asset (asset y todos sus assets hijos como order items)//////////////////
            
             Map<String,Object> step2 = (Map<String,Object>)inputMap.get('Step2-SelectAssetOrDocument');
             String seleccion = (String) step2.get('optionSelectAsset');
             
             step2 = new Map<String,Object>();
            
            if(seleccion == 'linea'){
            
              Map<String,Object> input = new Map<String,Object>();
              Map<String,Object> output = new Map<String,Object>();
              Map<String,Object> optionsMap = new Map<String,Object>();
              
              String idStr = (String)selectedAsset.get('AssetId');
              Id idval = idStr;                   
              idStr = idval;                    

              input.put('id', idStr); //Id del asset recibido

              input.put('accountId', (String)inputMap.get('ContextId')); //Id de la cuenta
              input.put('subaction','assetToOrder');
              input.put('methodName', 'assetToOrder');
              
              String fecha = Date.today().day() + '/' + Date.today().month() + '/' + Date.today().year();
              
              input.put('requestDate', fecha); //No puede crearse dos ordenes para un mismo asset en la misma fecha ni fecha anterior
            
              vlocity_cmt.CpqAppHandler cpqa = new vlocity_cmt.CpqAppHandler();
              cpqa.invokeMethod('assetToOrder', input, output, optionsMap);
              
              vlocity_cmt.JSONResult result = (vlocity_cmt.JSONResult) output.get('result');
              List<vlocity_cmt.JSONRecord> records = result.records;
              vlocity_cmt.JSONRecord record1 = records[0];
              Map<String,Object> fields = (Map<String,Object>)record1.fields;
              
              
              String idOrder = (String) fields.get('cartId');
              
              
              Order ordenCreada = [Select id from Order where id = : idOrder];
              
              ordenCreada.Delivery_Method__c = 'Presencial';
              ordenCreada.vlocity_cmt__OriginatingChannel__c = 'Presencial Agente';
              
              update ordenCreada;
            
            
        //////////////////Agrego a cada item de la orden los campos de suspension////////////
        
        List<OrderItem> items = new List<OrderItem>();
        
        items = [select id, orderId from OrderItem where orderid =: idOrder limit 10];
        
        Map<String,Object> mapaTipo = (Map<String,Object>)inputMap.get('Step1-SelectSuspensionOrReconnection');
        String tipo = (String) mapaTipo.get('SelectSuspensionOrReconnection');
        
         
        for(OrderItem itm : items){
            
            if(tipo == 'Suspension'){
            
            itm.vlocity_cmt__SubAction__c = 'Suspend-Operador';
            itm.vlocity_cmt__ProvisioningStatus__c = 'Suspend';
            
            }
            
            if(tipo == 'Reconection'){
                itm.vlocity_cmt__SubAction__c = 'Resume-Operador';
            itm.vlocity_cmt__ProvisioningStatus__c = 'Resume';
            }
        }
        
        update items;
         
        
        ///////////Checkout Order////////////////////
         
         Map<String,Object> input2 = new Map<String, Object>();
         Map<String,Object> output2 = new Map<String, Object>();
         Map<String,Object> options2 = new Map<String, Object>();
         
          List<Id> orderList = new List<Id>();
           
                
                orderList.add(idOrder);
            
            input2.put('orderIds', orderList);
            vlocity_cmt.VOIInvoker voi = vlocity_cmt.VOIInvoker.getInstance();
            voi.invoke('SubmitOrder', 'submitOrder', input2, output2, options2);
         
         
         //////////Submit de la orden a OM//////////
         
         vlocity_cmt.SimpleDecompositionController.decomposeOrder(idOrder);
         //vlocity_cmt.SimpleDecompositionController.startOrchestrationPlan(idOrder);
         
         ///////////////////////////////////////////
            } 
       }


private void createOrder(Map<String,Object> inputMap, Map<String,Object> outMap, Map<String,Object> options) {
            
         Map<String,Object> selectedAsset = (Map<String,Object>)inputMap.get('selectedAsset');

         ///////////////Create Order a partir de un Asset (asset y todos sus assets hijos como order items)//////////////////
            
            
            if(selectedAsset != null || !selectedAsset.isEmpty()){
            
              Map<String,Object> input = new Map<String,Object>();
              Map<String,Object> output = new Map<String,Object>();
              Map<String,Object> optionsMap = new Map<String,Object>();
              
              String idStr = (String)selectedAsset.get('AssetId');
              Id idval = idStr;                   
              idStr = idval;                    

              input.put('id', idStr); //Id del asset recibido

              input.put('accountId', (String)inputMap.get('ContextId')); //Id de la cuenta
              input.put('subaction','assetToOrder');
              input.put('methodName', 'assetToOrder');
              
              String fecha = Date.today().day() + '/' + Date.today().month() + '/' + Date.today().year();
              
              input.put('requestDate', fecha); //No puede crearse dos ordenes para un mismo asset en la misma fecha ni fecha anterior
            
              vlocity_cmt.CpqAppHandler cpqa = new vlocity_cmt.CpqAppHandler();
              cpqa.invokeMethod('assetToOrder', input, output, optionsMap);
              
              vlocity_cmt.JSONResult result = (vlocity_cmt.JSONResult) output.get('result');
              List<vlocity_cmt.JSONRecord> records = result.records;
              vlocity_cmt.JSONRecord record1 = records[0];
              Map<String,Object> fields = (Map<String,Object>)record1.fields;
              
              
              String idOrder = (String) fields.get('cartId');
            
            
        //////////////////Agrego a cada item de la orden los campos de suspension////////////
        
        List<OrderItem> items = new List<OrderItem>();
        
        items = [select id, orderId from OrderItem where orderid =: idOrder];
        
        Map<String,Object> mapaTipo = (Map<String,Object>)inputMap.get('Step1-SuspensionOrReconnection');
        String tipo = (String) mapaTipo.get('Radio1-SuspensionOrReconnection');
        
         
        for(OrderItem itm : items){
            
            if(tipo == 'Suspension'){
            
            itm.vlocity_cmt__SubAction__c = 'Suspend-Cliente';
            itm.vlocity_cmt__ProvisioningStatus__c = 'Suspend';
            
            }
            
            if(tipo == 'Reconexion'){
                itm.vlocity_cmt__SubAction__c = 'Resume-Cliente';
            itm.vlocity_cmt__ProvisioningStatus__c = 'Resume';
            }
        }
        
        update items;
         
        
        ///////////Checkout Order////////////////////
         
         Map<String,Object> input2 = new Map<String, Object>();
         Map<String,Object> output2 = new Map<String, Object>();
         Map<String,Object> options2 = new Map<String, Object>();
         
          List<Id> orderList = new List<Id>();
           
                
                orderList.add(idOrder);
            
            input2.put('orderIds', orderList);
            vlocity_cmt.VOIInvoker voi = vlocity_cmt.VOIInvoker.getInstance();
            voi.invoke('SubmitOrder', 'submitOrder', input2, output2, options2);
         
         
         //////////Submit de la orden a OM//////////
         
         vlocity_cmt.SimpleDecompositionController.decomposeOrder(idOrder);
         vlocity_cmt.SimpleDecompositionController.startOrchestrationPlan(idOrder);
         
         ///////////////////////////////////////////
            } 
            
        }

    private void getActiveOrSuspendedAssets (Map<String,Object> inputMap, Map<String,Object> outMap, Map<String,Object> options) {
        Boolean debug = false;

        if(debug){System.debug('InputMap: ' + inputMap);}
        if(debug){System.debug('OutputMap: ' + outMap);}
        if(debug){System.debug('OptionsMap: ' + options);}

        String accId = (String)options.get('accId');

        if(debug){System.debug('accId: ' + accId);}

        List<Asset> assets = [SELECT Id, imei__c, Asset_Brand__c, assetModel__c, Status, Sub_Status__c, Linked_Product_Family__c,
                                Name, vlocity_cmt__ActivationDate__c, MSISDN__c, Product2Id
                                FROM Asset
                                WHERE AccountId=:accId
                                AND Linked_Product_Family__c = 'Movil'
                                AND Status IN ('Active','Suspended')];


        if(debug){System.debug('List assets: ' + assets);}

        outMap.put('Assets',assets);

        if(debug){System.debug('outMap: ' + outMap);}

    }

    void createListChildCasesUnfraudBA(Map<String,Object> inputMap, Map<String,Object> outMap, Map<String,Object> options) {
        Id parentId = (Id)inputMap.get('DRId_Case');
       // Map<String, Object> clientInformation = (Map<String, Object>) inputMap.get('ClientInformation');
        List<Object> billingAccs = (List<Object>)options.get('BillingAccs');


        List<Case> listChildCases = new List<Case>();
        for(Object ba : billingAccs){
            Map<String, Object> baMap = (Map<String, Object>) ba; 
            Id accId =  (Id) baMap.get('Id');
            //string newId = myId.substring(0, 15);
            Case myCase = new Case();
            myCase.ParentId = parentId;
            myCase.AccountId = accId;
            myCase.Subject = 'Suspension/Habilitacion por Administrativas';
            myCase.Status = 'Cerrado';
            listChildCases.add(myCase);
        }
        insert listChildCases;
        outMap.put('Cases',listChildCases);
    }
    void createListChildCasesFraudBA(Map<String,Object> inputMap, Map<String,Object> outMap, Map<String,Object> options) {
        Id parentId = (Id)inputMap.get('DRId_Case');
       // Map<String, Object> clientInformation = (Map<String, Object>) inputMap.get('ClientInformation');
        List<Object> billingAccs = (List<Object>)options.get('FraudBillingAccs');


        List<Case> listChildCases = new List<Case>();
        for(Object ba : billingAccs){
            Map<String, Object> baMap = (Map<String, Object>) ba; 
            Id accId =  (Id) baMap.get('Id');
            //string newId = myId.substring(0, 15);
            Case myCase = new Case();
            myCase.ParentId = parentId;
            myCase.AccountId = accId;
            myCase.Subject = 'Suspension/Habilitacion por Administrativas';
            myCase.Status = 'Cerrado';
            listChildCases.add(myCase);
        }
        insert listChildCases;
        outMap.put('Cases',listChildCases);
    }
        void createListChildCasesAssets(Map<String,Object> inputMap, Map<String,Object> outMap, Map<String,Object> options) {
        Id parentId = (Id)inputMap.get('DRId_Case');
       // Map<String, Object> clientInformation = (Map<String, Object>) inputMap.get('ClientInformation');
        List<Object> billingAccs = (List<Object>)options.get('AssetsM');


        List<Case> listChildCases = new List<Case>();
        for(Object ba : billingAccs){
            Map<String, Object> baMap = (Map<String, Object>) ba; 
            Id assetId =  (Id) baMap.get('Id');
            //string newId = myId.substring(0, 15);
            Case myCase = new Case();
            myCase.ParentId = parentId;
            myCase.AssetId = assetId;
            myCase.Subject = 'Suspension/Habilitacion por Administrativas';
            myCase.Status = 'Cerrado';
            listChildCases.add(myCase);
        }
        insert listChildCases;
        outMap.put('Cases',listChildCases);
    }
}