objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Tangible__c</fullName>
        <formula>Product2.Tangible__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tangible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OrderProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Order Product from which this asset was created or most recently updated.</description>
        <label>Order Product</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>DeliveryDate__c</fullName>
        <description>Delivery Date - xOM</description>
        <inlineHelpText>Delivery Date - xOM</inlineHelpText>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Delivery_Method__c</fullName>
        <label>Delivery Method</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>vlocity_cmt__OriginatingChannel__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Delivery_Methods</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>OriginStoreLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Origin Store Location</label>
        <referenceTo>vlocity_cmt__BusinessSite__c</referenceTo>
        <relationshipLabel>Orders (Origin Store Location)</relationshipLabel>
        <relationshipName>OriginOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>FromStock__c</fullName>
        <description>It is saved from which inventory the reservation was made and then the sale. This can be paid for dismissal according to the type of inventory and if it is tangible or not, if you have to send it to invoice or not.</description>
        <label>From Stock</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A Location is set here, when the orderItem belongs to a Simcard and has a LineNumber associated to identify the location where the line is assigned</description>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__AssetId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The asset that this Order Product was pushed to by Order To Asset</description>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Order Product</relationshipLabel>
        <relationshipName>OrderProducts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Tangible__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indica si un producto es tangible o no</description>
        <label>Tangible</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Team_Member__c.object
<CustomObject>
    <description>Store the user assigned by work team in TA, this object is used to handle the security.</description>
    <fields>
        <fullName>User_member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to relate a user with the work team that it belongs to. Used in the security design done for TA.</description>
        <label>User member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Team__c</fullName>
        <description>This field is used to store the assignation of a team member (user) with a work team that it belongs to.</description>
        <label>Work Team</label>
        <referenceTo>WorkTeam__c</referenceTo>
        <relationshipLabel>Work Team Members</relationshipLabel>
        <relationshipName>Team_Members1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Work Team Member</label>
    <nameField>
        <displayFormat>T-{00000000}</displayFormat>
        <label>Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__BusinessSite__c.object
<CustomObject>
    <description>Sites track the service and retail locations where customers may obtain products or services from your organization or your partner organizations. In the communications industry, these represent retail stores or customer service locations. In the public sector, these represent the locations where benefits service providers operate. A site is located by address as well as geo-location data. A site must be defined for an account which may be a partner account or an internal organization account used to describe your company.</description>
    <fields>
        <fullName>Channel_Type_2__c</fullName>
        <description>Stores the level 2 of the type of channels.</description>
        <label>Channel Type 2</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Channel_Type_3__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>ChannelType2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel_Type_3__c</fullName>
        <description>Stores the level 3 of the type of channels.</description>
        <label>Channel Type 3</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ChannelType3</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel_Type__c</fullName>
        <description>Stores the first level of the type of channels.</description>
        <label>Channel Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Channel_Type_2__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>ChannelType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <description>Used to indicate the top level of the channels in the solution based in the value selected in the Channel_Type__c field.</description>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Channel_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Channel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__State__c</fullName>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Site</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/WorkTeam__c.object
<CustomObject>
    <description>Custom Object used to store the work teams hierarchy used to handle the security at Business Process level.</description>
    <fields>
        <fullName>Work_Place__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relates the Work Team with the Agency or Point of Sales.</description>
        <label>Work Place</label>
        <referenceTo>vlocity_cmt__BusinessSite__c</referenceTo>
        <relationshipLabel>Work Teams</relationshipLabel>
        <relationshipName>Work_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work Team</label>
    <nameField>
        <label>Work Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/taSalesChangeTerminalInWarrantyHandler.cls
global with sharing class taSalesChangeTerminalInWarrantyHandler implements vlocity_cmt.VlocityOpenInterface
{
    public static final String CONST_CHANNEL_PRESENTIAL = 'Presencial';
    public static final String CONST_TANGIBLE_CONSIGNADO = 'MTPL';
    global Boolean invokeMethod(String methodName, Map<String,Object> inputMap, Map<String,Object> outMap, Map<String,Object> options)
    {
    Boolean result = true;
    try
        {
        if (methodName.equals('ValidateCEGRazonSocial')){
             ValidateCEGRazonSocial(inputMap, outMap, options);
            }
        if (methodName.equals('ValidateTangibleConsignado')){
             ValidateTangibleConsignado(inputMap, outMap, options);
        }
        if (methodName.equals('validationTimeDefenseConsumer')){
             validationTimeDefenseConsumer(inputMap, outMap, options);
        }
        if (methodName.equals('ValidateClientMaterial')){
             ValidateClientMaterial(inputMap, outMap, options);
        }
        if (methodName.equals('ValidateSTEnElPais')){
             ValidateSTEnElPais(inputMap, outMap, options);
        }
         result = false;
        }
        catch(Exception e)
        {
            System.debug('ValidateCEGRazonSocial:invokeMethod -> exception: '+e);
            throw e;
        }
        return result;
    }

    public void ValidateCEGRazonSocial(Map<String,Object> inputMap, Map<String, Object> outMap, Map<String, Object> options)
    {
        try
        {        
            Id assetId = (Id) options.get('assetId');
            Boolean mismaRazonSocial = false;

            // En vlocity_cmt__OrderProductId__c se guarda la instancia de order item de la order creadora de asset.
        //    Id orderProduct = [SELECT vlocity_cmt__OrderProductId__c FROM Asset WHERE Id = :assetId].Id;

          //  Id origOrderId = [SELECT OrderId FROM OrderItem WHERE vlocity_cmt__AssetId__c = :orderProduct].Id;

            
            //Order order = [SELECT Id, OriginStoreLocation__c FROM Order WHERE Id = :origOrderId];
            
           list<Order> orders = AssetUtils.getOrderByAsset(assetId);
           System.debug('ELIANA');
            for(Order order : orders){
            vlocity_cmt__BusinessSite__c orderStore = [SELECT Id, Name, Channel__c, Channel_Type__c, Channel_Type_2__c, Channel_Type_3__c
                                                        FROM vlocity_cmt__BusinessSite__c
                                                        WHERE Id = :order.OriginStoreLocation__c];

  system.debug('Origin store location =====> '+ order.OriginStoreLocation__c);
            vlocity_cmt__BusinessSite__c userStore = [SELECT Id, Name, Channel__c, Channel_Type__c, Channel_Type_2__c, Channel_Type_3__c
                                                        FROM vlocity_cmt__BusinessSite__c
                                                    WHERE Id = :[SELECT Id, Work_Place__c
                                                                    FROM WorkTeam__c
                                                                    WHERE Id = :[SELECT Id, Work_Team__c
                                                                                    FROM Team_Member__c
                                                                                WHERE User_member__c = :UserInfo.getUserId()].Work_Team__c
                                                                    ].Work_Place__c];
            
            
            system.debug('userStore =====> '+userStore);
              // Misma razón social
                if(orderStore.Name == userStore.Name)
                {
                    mismaRazonSocial = true;
                }

                outMap.put('mismaRazonSocial', mismaRazonSocial);
            }
        }
        catch(Exception e)
        {
        System.debug('Exception Msg: ' + e.getMessage());
        System.debug('Exception Cause: ' + e.getCause());
        System.debug('Exception Stack Trace: ' + e.getStackTraceString());
        throw e;
        }
    }

    public void ValidateTangibleConsignado(Map<String,Object> inputMap, Map<String, Object> outMap, Map<String, Object> options)
    {
        try
        {
            //Id orderId = (Id) options.get('orderId');
            Id assetId = (Id) options.get('assetId');
            Boolean existTangibleConsignado = false;

            List<Order> orders = AssetUtils.getOrderByAsset(assetId);

            for(Order order: orders){
                //Se comprueban si existen TANGIBLES en orden
                List<OrderItem> orderItems = new List<OrderItem>();
                orderItems = [SELECT Id, Product2.ProductCode, Product2.Name, FromStock__c, Product2.Tangible__c
                            FROM OrderItem
                            WHERE OrderId = :order.Id];
                for(OrderItem item : orderItems)
                {
                    //Se comprueba si es tangible
                    if(item.Product2.Tangible__c)
                    {
                        //Se comprueba si es un tangible CONSIGNADO
                        if(item.FromStock__c.equals('CONST_TANGIBLE_CONSIGNADO'))
                        {
                            existTangibleConsignado = true;
                        }
                    }
                }

                outMap.put('existTangibleConsignado', existTangibleConsignado);
            }
        }
        catch(Exception e)
        {
        System.debug('Exception Msg: ' + e.getMessage());
        System.debug('Exception Cause: ' + e.getCause());
        System.debug('Exception Stack Trace: ' + e.getStackTraceString());
        throw e;
        }
    }
    
    public void validationTimeDefenseConsumer(Map<String,Object> inputMap, Map<String, Object> outMap, Map<String, Object> options){
        try{
            
            Id assetId = (Id) options.get('assetId');          
            Decimal timeLimit = 0;
            Date created;      
            
            List<Order> orders = AssetUtils.getOrderByAsset(assetId);

            for(Order order: orders){
                    vlocity_cmt__BusinessSite__c storeLocation = [SELECT Id, Channel__c, vlocity_cmt__State__c
                                                                FROM vlocity_cmt__BusinessSite__c
                                                                WHERE Id = :order.OriginStoreLocation__c];
                    if([SELECT count() FROM WarrantyTimeLimit__c WHERE Channel__c = :storeLocation.Channel__c AND LocationCode__c = :storeLocation.vlocity_cmt__State__c] > 0)
                        timeLimit = [SELECT TimeLimit__c
                                    FROM WarrantyTimeLimit__c
                                    WHERE LocationCode__c = :storeLocation.vlocity_cmt__State__c
                                        AND Channel__c = :storeLocation.Channel__c].TimeLimit__c;
                    else if([SELECT count() FROM WarrantyTimeLimit__c WHERE LocationCode__c = :storeLocation.vlocity_cmt__State__c AND Channel__c = null] > 0)
                        timeLimit = [SELECT TimeLimit__c
                                    FROM WarrantyTimeLimit__c
                                    WHERE LocationCode__c = :storeLocation.vlocity_cmt__State__c
                                        AND Channel__c = null].TimeLimit__c;
                    else
                        timeLimit = [SELECT TimeLimit__c
                                        FROM WarrantyTimeLimit__c
                                        WHERE Channel__c = null
                                        AND LocationCode__c = null].TimeLimit__c;
                    if(order.Delivery_Method__c.equals('CONST_CHANNEL_PRESENTIAL')){
                        created = date.newinstance(order.CreatedDate.year(), order.CreatedDate.month(), order.CreatedDate.day());
                    }else{
                        created = date.newinstance(order.DeliveryDate__c.year(), order.DeliveryDate__c.month(), order.DeliveryDate__c.day());
                    }

                    Boolean validTime = created.daysBetween(system.today()) <= timeLimit;

                outMap.put('validTime', validTime);
            }  
        }catch(Exception e){
            System.debug('Exception Msg: ' + e.getMessage());
            System.debug('Exception Cause: ' + e.getCause());
            System.debug('Exception Stack Trace: ' + e.getStackTraceString());
            throw e;
        }
    }

public void ValidateClientMaterial(Map<String,Object> inputMap, Map<String, Object> outMap, Map<String, Object> options)
   {
   try
    {
        boolean isValid = false;
        Id assetId = (Id) options.get('assetId');
        String inputSerial = [SELECT SerialNumber FROM Asset WHERE Id = : assetId].SerialNumber;
        Map<String, Object> serialsMap = new Map<String, Object>();
        serialsMap.put(inputSerial, null);
        //accedo a los valores del nuevo custom setting StockMovementConfiguration__c
        StockMovementConfiguration__c stockConf = StockMovementConfiguration__c.getInstance(UserInfo.getProfileId());
        
        String codDeposito = stockConf.Codigo_Deposito__c;
        String matClient = stockConf.Material_del_Cliente__c;
        List<String> stocks =  new  List<String> { matClient };
        
        IccidManager manager = new IccidManager();
        manager.ValidateSerialNumbers(serialsMap, codDeposito, stocks);
        Object serialValidado = serialsMap.get(inputSerial);
        
        if(serialValidado != null){
            isValid = true;
        }
        
        outMap.put('ValidateClientMaterial', isValid);
    }
    catch(Exception e){
           System.debug('Exception Msg: ' + e.getMessage());
           System.debug('Exception Cause: ' + e.getCause());
           System.debug('Exception Stack Trace: ' + e.getStackTraceString());
           throw e;
       }
   }
   
   public void ValidateSTEnElPais(Map<String,Object> inputMap, Map<String, Object> outMap, Map<String, Object> options)
   {
   try
    {
        Id assetId = (Id) options.get('assetId');
        
        List<String> atributoABuscar = new List<String>();
        atributoABuscar.add('Susceptible de Servicio Tecnico');

        Map<String,Object> valorAtributo = AssetAttributesUtils.getAssetAttribute(assetId, atributoABuscar);

        Boolean stValidation = Boolean.valueOf((String)valorAtributo.get('Susceptible de Servicio Tecnico'));
        
        outMap.put('ValidateST', stValidation);
    }
    catch(Exception e){
           System.debug('Exception Msg: ' + e.getMessage());
           System.debug('Exception Cause: ' + e.getCause());
           System.debug('Exception Stack Trace: ' + e.getStackTraceString());
           throw e;
       }
   }
}