objects/Crossobject__c.object
<CustomObject>
    <description>#Sales #Sprint12

multi-purpose object that allows you to configure templates of particular use such as content configurations of SMS, EMAILS, etc. and also allows you to track the sending and reply transactions of SMS, EMAILs, etc.

It has generic fields of type text, number and date which are added to several types of record types which are complemented with two fields of type pick list, thus a record type of type SMS can be combined with a sub value of type &quot;decision line&quot;</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>this field determines the relationship with the Account object.</description>
        <inlineHelpText>this field determines the relationship with the Account object.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cross Objects</relationshipLabel>
        <relationshipName>Cross_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CrossObjectName__c</fullName>
        <label>Name</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>DateTime1__c</fullName>
        <label>DateTime 1</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>this field determines the relationship with the Order object.</description>
        <inlineHelpText>this field determines the relationship with the Order object.</inlineHelpText>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Cross Objects</relationshipLabel>
        <relationshipName>Cross_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pendiente</fullName>
                </value>
                <value>
                    <fullName>Cerrado</fullName>
                </value>
                <value>
                    <fullName>Confirmado</fullName>
                </value>
                <value>
                    <fullName>Cancelado</fullName>
                </value>
                <value>
                    <fullName>Fallo Envio</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>String1__c</fullName>
        <description>generic string field type</description>
        <inlineHelpText>generic string field type</inlineHelpText>
        <label>String 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Cross Object</label>
    <nameField>
        <displayFormat>CO-{00000000}</displayFormat>
        <label>Crossobject Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cross Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/IFS_OrderSubmiterTest.cls
@isTest
public class IFS_OrderSubmiterTest {
    private static final String K_TIPO_JOB = 'Job Request';

    @isTest static void testResponseStatus200 () {
        Test.startTest();
        insertJob('801c00000007mQkAAI', '001c000001Px7D9');
        IFS_OrderSubmiter os = new IFS_OrderSubmiter();
        DataBase.executeBatch(os);
        Test.stopTest();    
    }    


    private static void insertJob (Id pOrderId, Id pAccountId) {
        Crossobject__c co = new Crossobject__c();
        co.order__c = pOrderId;
        co.CrossObjectName__c = K_TIPO_JOB + ' ' + pOrderId;
        co.Status__c = 'Pendiente';
        co.DateTime1__c = DateTime.now();
        co.Account__c = pAccountId;
        co.String1__c = 'F&F - Canal: Externo - Orden Id: ' + pOrderId;
        co.RecordTypeId = Schema.SObjectType.Crossobject__c.getRecordTypeInfosByName().get('External Channel').getRecordTypeId();
        insert co;
    }

}