objects/Order.object
<CustomObject>
    <fields>
        <fullName>Gestion__c</fullName>
        <label>Gestion</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cambio de SIM</fullName>
                </value>
                <value>
                    <fullName>Cambio de SIM por siniestro</fullName>
                </value>
                <value>
                    <fullName>Cambio de número</fullName>
                </value>
                <value>
                    <fullName>Cambio de titularidad</fullName>
                </value>
                <value>
                    <fullName>Desconexión</fullName>
                </value>
                <value>
                    <fullName>Nominacion</fullName>
                </value>
                <value>
                    <fullName>Cambio de Plan</fullName>
                </value>
                <value>
                    <fullName>Alta Baja Servicios</fullName>
                </value>
                <value>
                    <fullName>Compra de Pack</fullName>
                </value>
                <value>
                    <fullName>Venta</fullName>
                </value>
                <value>
                    <fullName>Alta</fullName>
                </value>
                <value>
                    <fullName>Recarga</fullName>
                </value>
                <value>
                    <fullName>Preactivacion Repro</fullName>
                </value>
                <value>
                    <fullName>Alta o Baja SVA</fullName>
                </value>
                <value>
                    <fullName>Conciliador</fullName>
                </value>
                <value>
                    <fullName>Conciliate</fullName>
                </value>
                <value>
                    <fullName>Suspension</fullName>
                </value>
                <value>
                    <fullName>Resume</fullName>
                </value>
                <value>
                    <fullName>Numero Gratis</fullName>
                </value>
                <value>
                    <fullName>Alta producto genérico</fullName>
                </value>
                <value>
                    <fullName>Cambio de Terminal</fullName>
                </value>
                <value>
                    <fullName>Cambio en Garantia</fullName>
                </value>
                <value>
                    <fullName>Reseteo de Cuota</fullName>
                </value>
                <value>
                    <fullName>Cambio de tiularidad</fullName>
                    <isActive>false</isActive>
                    <label>Cambio de tiularidad</label>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                    <isActive>false</isActive>
                    <label>Dormant</label>
                </value>
                <value>
                    <fullName>SimcardChange</fullName>
                    <isActive>false</isActive>
                    <label>SimcardChange</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__Action__c</fullName>
        <description>The action desired for this line item with values of Add, Change, Existing or Disconnect. Existing means no change is requested. Add is a request to add the item, Change is a request to change it. Disconnect is a request to remove it.</description>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Add</fullName>
                </value>
                <value>
                    <fullName>Change</fullName>
                </value>
                <value>
                    <fullName>Disconnect</fullName>
                </value>
                <value>
                    <fullName>Existing</fullName>
                </value>
                <value>
                    <fullName>Suspend</fullName>
                </value>
                <value>
                    <fullName>Resume</fullName>
                </value>
                <value>
                    <fullName>Activate</fullName>
                </value>
                <value>
                    <fullName>Modify</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__ProvisioningStatus__c</fullName>
        <description>(NOTE: The functionality of this field is replaced by the Action, Sub-Action and Fulfilment Status fields.) The desired provisioning action for the asset identified on this line item. Values include New (add), Active (no change), Changed or Deleted.</description>
        <label>Provisioning Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__SubAction__c</fullName>
        <description>The sub-action requested for this line item typically used for moves of service from one location to another with values of Move-Add and Move-Delete. Move-Add means this item is being added as part of the move and usually should be added before the previous service is disconnected. Move-Delete means this item is the service to be disconnected after the service is activated at the new location.</description>
        <label>Sub Action</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Move</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Full suspend</fullName>
                </value>
                <value>
                    <fullName>Baja-Baja</fullName>
                </value>
                <value>
                    <fullName>Baja-PortOut</fullName>
                </value>
                <value>
                    <fullName>Conciliate</fullName>
                </value>
                <value>
                    <fullName>Suspend-Fraude</fullName>
                </value>
                <value>
                    <fullName>Suspend-Voluntaria</fullName>
                </value>
                <value>
                    <fullName>Suspend-Portabilidad</fullName>
                </value>
                <value>
                    <fullName>Suspend-Siniestro</fullName>
                </value>
                <value>
                    <fullName>Resume-Siniestro</fullName>
                </value>
                <value>
                    <fullName>Resume-Fraude</fullName>
                </value>
                <value>
                    <fullName>Resume-Voluntaria</fullName>
                </value>
                <value>
                    <fullName>Change</fullName>
                </value>
                <value>
                    <fullName>Suspend-Robo</fullName>
                </value>
                <value>
                    <fullName>Suspend-Hurto</fullName>
                </value>
                <value>
                    <fullName>Suspend-Extravio</fullName>
                </value>
                <value>
                    <fullName>Resume-Portabilidad</fullName>
                    <isActive>false</isActive>
                    <label>Resume-Portabilidad</label>
                </value>
                <value>
                    <fullName>Suspend-Operador</fullName>
                    <isActive>false</isActive>
                    <label>Suspend-Operador</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/AssetConciliator.cls
global with sharing class AssetConciliator implements vlocity_cmt.VlocityOpenInterface {

    global AssetConciliator () {

    } 

    global Boolean invokeMethod(String methodName, Map<String,Object> inputMap, Map<String,Object> outMap, Map<String,Object> options) {
        Boolean result = true;
        
        try {
            if (methodName.equals('updateOrderToOM')){

                String parameterOrderId = (String) inputMap.get('orderFdoId');
                List<Object> assetIdList = (List<Object>) inputMap.get('assetIdList');

                if(parameterOrderId.length() > 0 ){ 
                    updateOrderToOM(parameterOrderId, methodName, assetIdList);
                }else{
                     
                    throw new FuncException('Error en Orden a Conciliar');
                    
                }

            }else if(methodName.equals('sendOrderToOM')){

                String orderId = (String) inputMap.get('sendOrderFdoId');
                                            
                sendOrderToOM(orderId);

            }
                result = true; 

            }catch(Exception e){
                throw e;
            }
        return result;
    }



    public static void updateOrderToOM(String orderId, String action, List<Object> assetIdList) {

        try {

            Order order = [SELECT Gestion__c , Status FROM Order where Id = :orderId];
            order.Gestion__c = 'Conciliate';

            update order;

            List<OrderItem> listOrderItems = [SELECT Id, Order.Id, vlocity_cmt__Action__c, vlocity_cmt__SubAction__c, vlocity_cmt__ProvisioningStatus__c FROM OrderItem WHERE Order.Id =:orderId];
            if (listOrderItems.size()==0){
                throw new FuncException('Error: No Existen OrderItems');
            }

            Map<Id,Object> standardPriceMap = new Map<Id,Object>();
            for(OrderItem getOrderItem : listOrderItems ){
                getOrderItem.vlocity_cmt__Action__c = 'Existing';
                getOrderItem.vlocity_cmt__SubAction__c = 'Conciliate' ;
                getOrderItem.vlocity_cmt__ProvisioningStatus__c = 'Active';
               
            }

            update listOrderItems;
           
            }catch(Exception ex) {

                throw ex;

            }

        }

    private static void sendOrderToOM(String orderIdToOM) {
        
        String responseOM = vlocity_cmt.SimpleDecompositionController.decomposeAndCreatePlanEx(orderIdToOM, false );
        Map<String, Object> mapResponseOM = (Map<String, Object>) JSON.deserializeUntyped(responseOM);

        if(mapResponseOM.get('isOk')!= true){
            throw new FuncException('Error: ' + mapResponseOM.get('errorMsg'));
        }
        

    }  
}