objects/Order.object
<CustomObject>
    <fields>
        <fullName>TrackingStatus__c</fullName>
        <label>Tracking status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pendiente de pago</fullName>
                </value>
                <value>
                    <fullName>Preparar pedido</fullName>
                </value>
                <value>
                    <fullName>Pendiente de entrega</fullName>
                </value>
                <value>
                    <fullName>Entregado</fullName>
                </value>
                <value>
                    <fullName>Pendiente de Validacion de Identidad</fullName>
                </value>
                <value>
                    <fullName>Cancelada - Timeout Validacion</fullName>
                </value>
                <value>
                    <fullName>Línea suspendida por mora</fullName>
                </value>
                <value>
                    <fullName>Línea suspendida por fraude</fullName>
                </value>
                <value>
                    <fullName>Línea suspendida voluntariamente</fullName>
                </value>
                <value>
                    <fullName>Línea suspendida por siniestro</fullName>
                </value>
                <value>
                    <fullName>Línea suspendida por Dorma</fullName>
                </value>
                <value>
                    <fullName>Línea de Baja</fullName>
                </value>
                <value>
                    <fullName>Cancelada - Time Out Store PickUp</fullName>
                </value>
                <value>
                    <fullName>Cobrado</fullName>
                </value>
                <value>
                    <fullName>Pago No Concretado</fullName>
                </value>
                <value>
                    <fullName>Recargado</fullName>
                </value>
                <value>
                    <fullName>Recarga SOS exitosa</fullName>
                </value>
                <value>
                    <fullName>Pendiente de Anulacion</fullName>
                </value>
                <value>
                    <fullName>Fraude</fullName>
                </value>
                <value>
                    <fullName>Cancelada - Validacion Rechazada</fullName>
                </value>
                <value>
                    <fullName>Cancelada - Timeout Caja</fullName>
                </value>
                <value>
                    <fullName>Anulado</fullName>
                </value>
                <value>
                    <fullName>Exitoso</fullName>
                </value>
                <value>
                    <fullName>Cancelada - Timeout</fullName>
                </value>
                <value>
                    <fullName>Inicial</fullName>
                </value>
                <value>
                    <fullName>Cerrada - No corresponde</fullName>
                </value>
                <value>
                    <fullName>Cerrada Exitosa - Reclamo</fullName>
                </value>
                <value>
                    <fullName>Pendiente de Anulación de Pago por Vencimiento de Plazo de Retiro</fullName>
                </value>
                <value>
                    <fullName>Pendiente de Anulación de Pago</fullName>
                </value>
                <value>
                    <fullName>Pago Fallido</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OriginatingChannel__c</fullName>
        <description>Channel can be used to drive Eligibility/Compatibility/Recommendations/Pricing/Other implementations, e.g. Certain Product Bundles are only available on the Web or Call Center channel but not via the Retail and Dealer channels OR A product may have a different price when sold via the Web than sold via the Retail channel, etc.</description>
        <label>Originating Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WEB</fullName>
                </value>
                <value>
                    <fullName>Call Center</fullName>
                </value>
                <value>
                    <fullName>Retails</fullName>
                </value>
                <value>
                    <fullName>Mayorista</fullName>
                </value>
                <value>
                    <fullName>Agentes</fullName>
                </value>
                <value>
                    <fullName>Oficinas Comerciales</fullName>
                </value>
                <value>
                    <fullName>E-Commerce</fullName>
                </value>
                <value>
                    <fullName>Administración de Ventas</fullName>
                </value>
                <value>
                    <fullName>APP</fullName>
                </value>
                <value>
                    <fullName>Cooperativas</fullName>
                </value>
                <value>
                    <fullName>Ejecutivos</fullName>
                </value>
                <value>
                    <fullName>Emprendimientos</fullName>
                </value>
                <value>
                    <fullName>IVR</fullName>
                </value>
                <value>
                    <fullName>SMS</fullName>
                </value>
                <value>
                    <fullName>Social Media</fullName>
                </value>
                <value>
                    <fullName>USSD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__PriceListId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price List</label>
        <referenceTo>vlocity_cmt__PriceList__c</referenceTo>
        <relationshipLabel>Orders Using This Price List</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>TechCare_Repair_Estimate</fullName>
        <active>true</active>
        <label>Presupuesto de Reparacion</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__PriceList__c.object
<CustomObject>
    <description>A price list represents the pricing for the products and services that your company offers. A base price list defines the baseline pricing for your products and services. A child price list inherits all the pricing from the base price list and contains exceptions to the baseline pricing.</description>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ta_sales_PendingAnnulledOrdersBatchTest.cls
@isTest
public class ta_sales_PendingAnnulledOrdersBatchTest {
    static testMethod void testMethod1() 
    {
        SalesOrderAnnulmentTimeout__c cs = new SalesOrderAnnulmentTimeout__c();
        cs.Name = 'DefaultTimeout';
        cs.TimeoutDays__c = 0;
        
        insert cs;
        
        vlocity_cmt__PriceList__c taPriceList = TestDataFactory.createPriceList('Telecom Price List');
        
    	Id orderRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'TechCare_Repair_Estimate' AND SobjectType = 'Order' LIMIT 1].Id;

        Account acc = new Account();
        acc.Name ='Name';
        
        insert acc;        

        Order o = new Order(Name='TestOrder',
                            RecordTypeId = orderRecordTypeId,
                            AccountId=acc.Id,
                            EffectiveDate=Date.today(),
                            Status='Draft',
                            TrackingStatus__c = 'Pendiente de Anulacion',
                            Pricebook2Id =Test.getStandardPricebookId(),
                            vlocity_cmt__PriceListId__c=taPriceList.Id,
                            vlocity_cmt__OriginatingChannel__c='Agentes');

        insert o;

        Order o2 = new Order(Name='TestOrder2',
                            RecordTypeId = orderRecordTypeId,
                            AccountId=acc.Id,
                            EffectiveDate=Date.today(),
                            Status='Draft',
                            TrackingStatus__c = 'Pendiente de Anulacion',
                            Pricebook2Id =Test.getStandardPricebookId(),
                            vlocity_cmt__PriceListId__c=taPriceList.Id,
                            vlocity_cmt__OriginatingChannel__c='Agentes');

        insert o2;
        
        Test.setCreatedDate(o.Id, DateTime.newInstance(2018,01,12));
        
        Test.startTest();

            ta_sales_PendingAnnulledOrdersBatch obj = new ta_sales_PendingAnnulledOrdersBatch();
            DataBase.executeBatch(obj); 
            
        Test.stopTest();
    }
}