objects/User.object
<CustomObject>
    <fields>
        <fullName>Work_Team__c</fullName>
        <description>Stores the name of the work team that the user belongs to. It is loaded by development to control the vlocity actions available for a user.</description>
        <externalId>true</externalId>
        <label>Work Team</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/WorkTeam__c.object
<CustomObject>
    <description>Custom Object used to store the work teams hierarchy used to handle the security at Business Process level.</description>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the manager of the workplace</description>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Workplaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field used to handle the hierarchy relationship between the Work Teams.</description>
        <label>Parent Team</label>
        <referenceTo>WorkTeam__c</referenceTo>
        <relationshipLabel>Child Work Teams</relationshipLabel>
        <relationshipName>Workplaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work Team</label>
    <nameField>
        <label>Work Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/taCareAdjustments.cls
public with sharing class taCareAdjustments {
	
	  //@InvocableMethod(label='Escalar Caso Adjustment' description='Actualiza el OwnerId según el Mager del Parent WorkTeam en la gerarquía del Owner actual')
	  static public void escalarCaso(List<Case> cases) {
	  	System.debug('Escalar Caso Adjustment');
	  		
	  		try {
	  			if (cases != null && !cases.isEmpty()) {
	  				Case myCase = [SELECT Subject, Status, OwnerId FROM Case WHERE Id =: cases.get(0).Id];
	  				
	  				
	  				if(myCase.Subject == 'Inconvenientes con cargos tasados y facturados' && myCase.Status == 'En espera de ejecución') {
	  					System.debug('DERIVANDO EL CASO POR VENCIMIENTO DE SLA');
	  					User user = [select Work_Team__c from User where Id =: myCase.OwnerId];
	  					if(user.Work_Team__c != null){
	  						WorkTeam__c workTeam = [select Parent_Team__c from WorkTeam__c where Id =: user.Work_Team__c];
				  			
				  			if (workTeam.Parent_Team__c != null) {
				  				WorkTeam__c workTeamParet = [select Manager__c from WorkTeam__c where Id =: workTeam.Parent_Team__c];
				  				myCase.OwnerId = workTeamParet.Manager__c;
				  			}
	  					}
			  			
			  			myCase.Status = 'Derivada';
			  			update myCase;
	  				}
	  			}
	  			
	  		} catch (Exception e) {
	  			System.debug(e.getMessage());
	  		}
	  }
    
}