objects/WorkTeam__c.object
<CustomObject>
    <description>Custom Object used to store the work teams hierarchy used to handle the security at Business Process level.</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>PFTA-8791 - Used to indicate if the work team is active or not.</description>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field used to handle the hierarchy relationship between the Work Teams.</description>
        <label>Parent Team</label>
        <referenceTo>WorkTeam__c</referenceTo>
        <relationshipLabel>Child Work Teams</relationshipLabel>
        <relationshipName>Workplaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Name__c</fullName>
        <description>Stores the name of the division (team).</description>
        <externalId>true</externalId>
        <label>Team Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>WorkteamLevel__c</fullName>
        <label>Workteam Level</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Work Team</label>
    <nameField>
        <label>Work Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WorkTeamWrapper.cls
/**
* @author       Norwill Gutiérrez href=<ngutierrez@aconcaguabs.com>
* Project:      Telecom Security
* Description:  Wrapper Class for Security Hierarchy
*
* Changes (Version)
* -------------------------------------
*      No.    Date          Author                 Description
*      -----  ----------    --------------------   ---------------
*      1.0    2018-03-09    Norwill Gutiérrez      Class creation.
*************************************************************************************************************/
public with sharing class WorkTeamWrapper {
	public Boolean checked{ get; set; }
	public WorkTeam__c wt { get; set;}    
    public Integer wtPosInSet { get; set;}
    public String parent { get; set;}
    public Integer wtSetSize { get; set;}
    public Work_Team_Permission__c wtP { get; set;}

    public String parentName { get; set;}
    public String teamName { get; set;}
    

    public WorkTeamWrapper(WorkTeam__c wtN, String vlcActionName, Integer totalChildrens, Integer counter, String prefixP, Boolean isTopLevel){
        try{
            wt = wtN;
            wtSetSize = totalChildrens;
            wtP = null; 
            if(isTopLevel){
                parent = String.valueOf(wtN.WorkteamLevel__c);
            }else{
                parent = prefixP + String.valueOf(counter);
            }
            
            if(wtP != null){ 
                checked = wtP.Is_Active__c;
            }else{
                checked = false;
            }
        }catch(Exception e){
            wtP = null; 
            checked = false;              
        }
    }

    // public WorkTeamWrapper(WorkTeam__c wtN){
    //     try{
    //         teamName = wtN.Team_Name__c;
    //         if(String.isNotBlank(wtN.Parent_Team__c)){
    //             parentName = wtN.Parent_Team__c;
    //         }else{
    //             parentName = wtN.Team_Name__c;
    //         }
    //     }catch(Exception e){

    //     }
    // }

    public static void setPermissions(Map<Id, WorkTeamWrapper> teamNodes, String vlcActionName){     
        List<Work_Team_Permission__c> wtpResult = [SELECT 
                                                        Id, Work_Team__c, RecordTypeId, Permission_Set_API_Name__c, Is_Active__c
                                                    FROM 
                                                        Work_Team_Permission__c 
                                                    WHERE 
                                                        Work_Team__c = :teamNodes.keySet() AND Permission_Set_API_Name__c = :vlcActionName]; 

        for(Work_Team_Permission__c wtP :wtpResult){
            teamNodes.get(wtP.Work_Team__c).checked = wtP.Is_Active__c;
        }                                                        
    }
}